
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  backend: "s3://{{ .Values.backend.bucketName }}"
  secretsProvider:  "{{ .Values.secretProvider }}"
  envRefs:
    AWS_DEFAULT_REGION:
      type: Literal
      literal:
        value: "{{ .Values.region }}"
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: "{{ .Values.aws.secretName }}"
        key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: "{{ .Values.aws.secretName }}"
        key: AWS_SECRET_ACCESS_KEY
  #    AWS_SESSION_TOKEN:
  #      type: Secret
  #      secret:
  #        name: pulumi-aws-secret
  #        key: AWS_SESSION_TOKEN
  stack: "{{ .Values.stack.name }}"
  projectRepo: "{{ .Values.stack.repo.url }}"
  repoDir: "{{ .Values.stack.repo.path }}"
  branch: "{{ .Values.stack.repo.revision }}"
  destroyOnFinalize: "{{ .Values.stack.destroyOnFinalize | default false }}"